// examples/playground/src/components/vue/PreviewIsland.vue
<script setup lang="ts">
import { onMounted, onUnmounted, shallowRef } from "vue";
import type { CmsEngine } from "better-content/core";
import { ready } from "../../lib/engine";
import { editMode } from "../../lib/editMode";
import PreviewFrame from "./PreviewFrame.vue";

const engine = shallowRef<CmsEngine | null>(null);
const editing = shallowRef(editMode.get());
let stop = () => {};

onMounted(async () => {
  stop = editMode.subscribe(() => (editing.value = editMode.get()));
  engine.value = await ready;
});
onUnmounted(() => stop());
</script>

<template>
  <PreviewFrame v-if="engine" :engine="engine" :editing="editing" />
  <p v-else class="island-loading">starting Vue preview...</p>
</template>

// examples/playground/src/components/svelte/PreviewIsland.svelte
<script lang="ts">
  import { ready } from "../../lib/engine";
  import { editModeStore } from "../../lib/editMode";
  import PreviewFrame from "./PreviewFrame.svelte";
</script>

{#await ready}
  <p class="island-loading">starting Svelte preview...</p>
{:then engine}
  <PreviewFrame {engine} editing={$editModeStore} />
{/await}
