// examples/playground/src/components/react/MarkdownCard.tsx
import type { CmsEngine } from "better-content/core";
import { useMarkdownEditor } from "better-content/react";
import { renderMarkdown } from "../../lib/markdown";

const ITEM_ID = "note-react";

export default function MarkdownCard({
  engine,
  editing,
}: {
  engine: CmsEngine;
  editing: boolean;
}) {
  const md = useMarkdownEditor({
    initialValue: engine.getItem<{ body?: string }>("page", ITEM_ID)?.body ?? "",
    onSave: async (content) => {
      engine.editField("page", ITEM_ID, "body", content);
      await engine.saveItem("page", ITEM_ID);
    },
  });

  return (
    <article className="island" data-framework="react">
      <header className="island__bar">
        <span className="island__dot"></span>
        <span className="island__name">React</span>
        <code className="island__hook">useMarkdownEditor()</code>
        <span className="island__state">{md.charCount} chars</span>
      </header>
      <div className="island__body">
        <p className="island__path">page / {ITEM_ID}.body</p>
        {editing ? (
          <>
            <div className="draft__tools">
              <button type="button" onClick={() => md.insert("**", "**", "bold")}>
                bold
              </button>
              <button
                type="button"
                onClick={() => md.insert("[", "](https://)", "link")}
              >
                link
              </button>
              <button type="button" onClick={() => md.insert("`", "`", "code")}>
                code
              </button>
            </div>
            <textarea
              ref={md.textareaRef}
              className="draft__area"
              rows={7}
              spellCheck={false}
              value={md.value}
              onChange={(event) => md.setValue(event.target.value)}
            />
            <div className="draft__actions">
              <button
                type="button"
                className="draft__button"
                onClick={() => md.reset()}
              >
                Reset
              </button>
              <button
                type="button"
                className="draft__button draft__button--mark"
                onClick={() => void md.save()}
              >
                Save draft
              </button>
            </div>
          </>
        ) : (
          <div
            className="draft__rendered"
            dangerouslySetInnerHTML={{ __html: renderMarkdown(md.value) }}
          />
        )}
      </div>
    </article>
  );
}

// examples/playground/src/components/vue/MarkdownCard.vue
<script setup lang="ts">
import type { CmsEngine } from "better-content/core";
import { useMarkdownEditor } from "better-content/vue";
import { renderMarkdown } from "../../lib/markdown";

const props = defineProps<{ engine: CmsEngine; editing: boolean }>();

const ITEM_ID = "note-vue";

const md = useMarkdownEditor({
  initialValue:
    props.engine.getItem<{ body?: string }>("page", ITEM_ID)?.body ?? "",
  onSave: async (content) => {
    props.engine.editField("page", ITEM_ID, "body", content);
    await props.engine.saveItem("page", ITEM_ID);
  },
});
const { textareaRef } = md;
</script>

<template>
  <article class="island" data-framework="vue">
    <header class="island__bar">
      <span class="island__dot"></span>
      <span class="island__name">Vue</span>
      <code class="island__hook">useMarkdownEditor()</code>
      <span class="island__state">{{ md.charCount.value }} chars</span>
    </header>
    <div class="island__body">
      <p class="island__path">page / {{ ITEM_ID }}.body</p>
      <template v-if="editing">
        <div class="draft__tools">
          <button type="button" @click="md.insert('**', '**', 'bold')">bold</button>
          <button type="button" @click="md.insert('[', '](https://)', 'link')">
            link
          </button>
          <button type="button" @click="md.insert('`', '`', 'code')">code</button>
        </div>
        <textarea
          ref="textareaRef"
          class="draft__area"
          rows="7"
          spellcheck="false"
          :value="md.value.value"
          @input="md.setValue(($event.target as HTMLTextAreaElement).value)"
        ></textarea>
        <div class="draft__actions">
          <button type="button" class="draft__button" @click="md.reset()">
            Reset
          </button>
          <button
            type="button"
            class="draft__button draft__button--mark"
            @click="md.save()"
          >
            Save draft
          </button>
        </div>
      </template>
      <div v-else class="draft__rendered" v-html="renderMarkdown(md.value.value)"></div>
    </div>
  </article>
</template>
